application: moses
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /proxxxxy/.*
  script: proxy/fetch.py

- url: /fetch.py
  script: fetch.py

- url: /.*
  script: helloworld.py
