application: moses
version: 2
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /proxy/.*
  script: proxy/fetch.py

- url: /proxy/fetch.py
  script: proxy/fetch.py

- url: /.*
  script: helloworld.py
